table Sheet1
	lineageTag: cded83ec-184e-4942-83b2-c0acf68e1e9f

	column 'Customer Name'
		dataType: string
		lineageTag: 2d3f1a80-f665-4584-b2f0-369b7eaf578f
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Feedback
		dataType: string
		lineageTag: e42168a1-6cf0-49cb-a3db-dad180c977b4
		summarizeBy: none
		sourceColumn: Feedback

		annotation SummarizationSetBy = Automatic

	column 'Sentiment Score'
		dataType: double
		lineageTag: 1762ab84-8524-40a6-9f5c-5b47a02e32b7
		summarizeBy: sum
		sourceColumn: Sentiment Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sentiment Category'
		dataType: string
		lineageTag: 29ec2d40-ac19-45c4-b947-c8024da6502b
		summarizeBy: none
		sourceColumn: Sentiment Category

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\LAPTOP HUB\Downloads\Insurance_Feedback_Sentiment_Categorized.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer Name", type text}, {"Feedback", type text}, {"Sentiment Score", type number}, {"Sentiment Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

